overrides:
  - files: "*.js"
    options:
      printWidth: 150
      singleQuote: true
      bracketSpacing: true
      tabWidth: 2
      useTabs: false
      semi: true

  - files: "*.html"
    options:
      printWidth: 250
      tabWidth: 2
      useTabs: false

  - files: "*.css"
    options:
      tabWidth: 2
      useTabs: false

  - files: "*.scss"
    options:
      printWidth: 100000
      tabWidth: 2
      useTabs: false

  - files: "*.vue"
    options:
      printWidth: 150
      singleQuote: true
      bracketSpacing: true
      tabWidth: 2
      useTabs: false
      semi: true

  - files: "*.ts"
    options:
      printWidth: 150
      singleQuote: true
      bracketSpacing: true
      tabWidth: 2
      useTabs: false
      semi: true
